# Generated by Django 3.0.7 on 2020-07-06 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('IDLE', 'IDLE'), ('BUSY', 'BUSY')], default='IDLE', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestFilePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('path', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestRunRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('requested_by', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('RUNNING', 'RUNNING'), ('FAILED', 'FAILED'), ('CREATED', 'CREATED'), ('RETRYING', 'RETRYING'), ('FAILED_TO_START', 'FAILED_TO_START')], default='CREATED', max_length=64)),
                ('logs', models.TextField(blank=True)),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TestEnvironment')),
                ('path', models.ManyToManyField(to='api.TestFilePath')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
