# Generated by Django 4.0.1 on 2022-02-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200706_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfilepath',
            name='filePath',
            field=models.FileField(null=True, unique=True, upload_to='tests/'),
        ),
    ]
